SchoolManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("sms.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sms/urls.py
from django.urls import path
from . views import *

urlpatterns = [
    # Home
    path('', home_view, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('admission/', admission, name='admission'),
    path('logout/', logout_view, name='logout'),
    # Admin
    path('register_approvals/', register_approvals, name='register_approval'),
    path('admission_messages/', admission_messages, name='admission_messages'),
    path('contact_messages/', contact_messages, name='contact_messages'),
    path('approve_user/<int:user_id>/<str:user_type>/', approve_user, name='approve_user'),
    path('reject_user/<int:user_id>/<str:user_type>/', reject_user, name='reject_user'),
    path('classes/', classes, name='classes'),
    path('classes/update/<int:class_id>/', update_class, name='update_class'),
    path('delete_class/<int:class_id>/', delete_class, name='delete_class'),
    path('sections/', sections, name='sections'),
    path('update_sections/', update_sections, name='update_sections'),
    path('delete_sections/', delete_sections, name='delete_sections'), 
    path('subjects/', subjects, name='subjects'),
    path('update_subjects/', update_subjects, name='update_subjects'),
    path('delete_subjects/', delete_subjects, name='delete_subjects'), 
    path('exam/', exam, name='exam'),
    path('departments/', departments, name='departments'),
    path('edit_department/<int:department_id>/', edit_department, name='edit_department'),
    path('academic_session/', academic_session, name='academic_session'),
    path('employee_category/', employee_category, name='employee_category'),
    path('leave_approval/', leave_approval, name='leave_approval'),
    path('update_leave_approval/<int:pk>/<str:status>/', update_leave_approval, name='update_leave_approval'),
    path('fees/', fees, name='fees'),
    path('fees_payment/', fees_payment, name='fees_payment'),
    path('salary_payment/', salary_payment, name='salary_payment'),
    path('busroute/', busroute, name='busroute'),
    path('send_sms/', send_sms, name='send_sms'),
    path('attendance/', attendance, name='attendance'),
    path('timetable/', timetable, name='timetable'),
    # Staff
    path('staff-dashboard/', staff_portal, name='staff_portal'),
    path('staff_attendance/', staff_attendance, name='staff_attendance'),
    path('staff_timetable/', staff_timetable, name='staff_timetable'),
    path('staff_leave_request/', staff_leave_request, name='staff_leave_request'),
    path('staff_payslip/', staff_payslip, name='staff_payslip'),
    path('staff_bus/', staff_bus_details, name='staff_bus'),
    # Faculty
    path('faculty-dashboard/', faculty_portal, name='faculty_portal'),
    path('faculty_attendance/', faculty_attendance, name='faculty_attendance'),
    path('leave_request/', leave_request, name='leave_request'),
    path('faculty_timetable/', faculty_timetable, name='faculty_timetable'),
    path('faculty_payslip/', faculty_payslip, name='faculty_payslip'),
    path('marks/', marks, name='marks'),
    path('faculty_bus/', faculty_bus_details, name='faculty_bus'),
    # Student
    path('student_dashboard/', student_portal, name='student_portal'),
    path('student_classes/', student_classes, name='student_classes'),
    path('student_attendance/', student_attendance, name='student_attendance'),
    path('student_timetable/', student_timetable, name='student_timetable'),
    path('exam_timetable/', exam_timetable, name='exam_timetable'),
    path('student_marks/', student_marks, name='student_marks'),
    # Parent
    path('parent-dashboard/', parent_portal, name='parent_portal'),
    path('parent_classes/', parent_classes, name='parent_classes'),
    path('parent_attendance/', parent_attendance, name='parent_attendance'),
    path('parent_timetable/', parent_timetable, name='parent_timetable'),
    path('parent_exam_timetable/', parent_exam_timetable, name='parent_exam_timetable'),
    path('parent_marks/', parent_marks, name='parent_marks'),
    path('parent_fees/', parent_fees, name='parent_fees'),
    path('create_order/', create_order, name='create_order'),
    path('paytm/callback/', payment_callback, name='payment_callback'),
    path('parent_bus/', parent_bus_details, name='parent_bus'),

    
]

sms/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class StudentAdmission(models.Model):
    name = models.CharField(max_length=30)
    date_of_birth = models.DateField()
    email = models.EmailField()
    address = models.TextField()
    class_of_admission = models.CharField(max_length=10)
    previous_school = models.CharField(max_length=30)
    parent_name = models.CharField(max_length=30)
    parent_contact = models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Class(models.Model):
    name = models.CharField(max_length=10)
    def __str__(self):
        return self.name if self.name else 'Unnamed Class'
    
class Section(models.Model):
    name = models.CharField(max_length=50)
    class_linked = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, default=None)
    def __str__(self):
        return self.name if self.name else 'Unnamed Section'

class Subject(models.Model):
    class_linked = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, default=None)
    section_linked = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, default=None)
    subjectname = models.CharField(max_length=100, null=True)
    def __str__(self):
        return self.subjectname if self.subjectname else 'Unnamed Subject'

class Exam(models.Model):
    EXAM_TYPES = [
        ('Quarterly', 'Quarterly'),
        ('Half Yearly', 'Half Yearly'),
        ('Annual', 'Annual'),
        ('Unit Test', 'Unit Test'),
    ]
    exam_type = models.CharField(max_length=20, choices=EXAM_TYPES)
    unit_test_number = models.PositiveSmallIntegerField(null=True, blank=True)
    class_linked = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, default=None)
    section_linked = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, default=None)
    file = models.FileField(upload_to='exam_timetable/') 

class Department(models.Model):
    name = models.CharField(max_length=100)
    faculty = models.ManyToManyField('Faculty', related_name='departments')
    def __str__(self):
        return self.name

class AcademicSession(models.Model):
    session_name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()

class LeaveRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, default=None)
    start_date = models.DateField()
    end_date = models.DateField()
    reason = models.TextField()
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Approved', 'Approved'),
        ('Declined', 'Declined'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    LEAVE_TYPE_CHOICES = (
        ('Casual Leave', 'Casual Leave'),
        ('Sick Leave', 'Sick Leave'),
        ('Maternity Leave', 'Maternity Leave'),
        ('Paternity Leave', 'Paternity Leave'),
    )
    leave_type = models.CharField(max_length=20, choices=LEAVE_TYPE_CHOICES, null=True, default=None)
    created_at = models.DateTimeField(auto_now_add=True)
    status_changed = models.DateTimeField(null=True, blank=True)
    notified = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.pk:
            orig = LeaveRequest.objects.get(pk=self.pk)
            if orig.status != self.status:
                self.status_changed = timezone.now()
                self.notified = False
        super().save(*args, **kwargs)

    def get_user_type(self):
        if hasattr(self.user, 'staff'):
            return 'Staff', self.user.staff.name
        elif hasattr(self.user, 'faculty'):
            return 'Faculty', self.user.faculty.name
    def __str__(self):
        user_type, user_name = self.get_user_type()
        return f"Leave request by {user_name} ({user_type})"

class BusRoute(models.Model):
    route_name = models.CharField(max_length=25)
    bus_number = models.CharField(max_length=10)
    driver_name = models.CharField(max_length=25)
    driver_number = models.CharField(max_length=10)

class PickupLocation(models.Model):
    bus_route = models.ForeignKey(BusRoute, related_name='pickup_locations', on_delete=models.SET_NULL, null=True, default=None)
    location = models.CharField(max_length=100)
    time = models.TimeField()

class DropoffLocation(models.Model):
    bus_route = models.ForeignKey(BusRoute, related_name='dropoff_locations', on_delete=models.SET_NULL, null=True, default=None)
    location = models.CharField(max_length=100)
    time = models.TimeField()

class ContactMessage(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, default=None)
    staff_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)
    email = models.EmailField()
    gender = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=10)
    location = models.CharField(max_length=25, null=True, default=None)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Faculty(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, default=None)
    faculty_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)
    email = models.EmailField()
    gender = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=10)
    location = models.CharField(max_length=25, null=True, default=None)
    class_assigned = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, default=None)
    section_assigned = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, default=None)
    is_approved = models.BooleanField(default=False)

    class Meta:
        unique_together = ('class_assigned', 'section_assigned')

    def __str__(self):
        return self.name

class Students(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, default=None)
    student_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=25)
    email = models.EmailField()
    roll_number = models.CharField(max_length=10, unique=True)
    class_name = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, default=None)
    section_linked = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, default=None)
    location = models.CharField(max_length=25, null=True, default=None)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Parents(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, default=None)
    parent_id = models.AutoField(primary_key=True)
    parent_name = models.CharField(max_length=25)
    children = models.ManyToManyField(Students)
    contact_number = models.CharField(max_length=10)
    location = models.CharField(max_length=20)
    is_approved = models.BooleanField(default=False)

class BusFees(models.Model):
    location = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

class TuitionFees(models.Model):
    class_linked = models.OneToOneField(Class, on_delete=models.SET_NULL, null=True, default=None)
    amount = models.DecimalField(max_digits=10, decimal_places=2)

class MessFees(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)

class Payment(models.Model):
    PAYMENT_CHOICES = (
        ('Cash', 'Cash'),
        ('Credit Card', 'Credit Card'),
        ('Bank Transfer', 'Bank Transfer'),
        ('Demand Draft', 'Demand Draft'),
        ('Cheque', 'Cheque'),
    )
    FEES_CHOICES = (
        ('Bus Fees', 'Bus Fees'),
        ('Mess Fees', 'Mess Fees'),
        ('Tuition Fees', 'Tuition Fees'),
    )
    class_linked = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, default=None)
    section_linked = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True, default=None)
    student = models.ForeignKey(Students, on_delete=models.SET_NULL, null=True, default=None)
    payment_type = models.CharField(max_length=20, choices=PAYMENT_CHOICES, null=True, default=None)
    fees_type = models.CharField(max_length=20, choices=FEES_CHOICES, null=True, default=None)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, default=None)
    receipt_number = models.CharField(max_length=20)
    invoice = models.FileField(upload_to='invoices/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class StaffLeave(models.Model):
    month = models.CharField(max_length=20)
    staff_leaves = models.PositiveIntegerField(default=0)

class FacultyLeave(models.Model):
    month = models.CharField(max_length=20)
    faculty_leaves = models.PositiveIntegerField()

class StaffSalary(models.Model):
    staff = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to='staff_payslips/')
    month = models.CharField(max_length=20)
    year = models.IntegerField()

class FacultySalary(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.SET_NULL, null=True)
    file = models.FileField(upload_to='faculty_payslips/')
    month = models.CharField(max_length=20)
    year = models.IntegerField()

class FacultyAttendance(models.Model):
    file = models.FileField(upload_to='faculty_attendance/')
    date = models.DateField(auto_now_add=True)

class StaffAttendance(models.Model):
    file = models.FileField(upload_to='staff_attendance/')
    date = models.DateField(auto_now_add=True)

class StudentAttendance(models.Model):

sms/templates/Home/Admission.html
{% load static %}
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=7">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="keywords" content="">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Admission</title>
    <link rel="stylesheet" href="{% static 'sms/css/Home.css' %}">
    <link rel="apple-touch-icon" href="{% static 'sms/img/school-logo (2).png' %}">
    <link rel="shortcut icon" href="{% static 'sms/img/school-logo (2).png' %}" type="image/x-icon">
</head>

<body>
    <div class="bg_img_placeholder">
        <header>
            <div class="nav_bar_placeholder">
                <div class="img_placeholder">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'sms/img/school-logo (2).png' %}" alt="School_Logo">
                    </a>
                </div>

                <!-- Burger Menu Icon -->
                <div class="burger-menu">
                    ☰
                </div>

                <!-- Navbar Content (will be hidden on mobile) -->
                <div class="navbar_placeholder">
                    <div class="navbar">
                        <nav>
                            <ul class="nav_links">
                                <li class="nav_link" id="home-link"><a href="{% url 'home' %}"><span>Home</span></a>
                                </li>
                                <li class="nav_link" id="about-link"><a href="{% url 'about' %}"><span>About</span></a>
                                </li>
                                <li class="nav_link" id="contact-link"><a
                                        href="{% url 'contact' %}"><span>Contact</span></a>
                                </li>
                                <li class="nav_link" id="admission-link"><a href="{% url 'admission' %}"><span>New
                                            Admission</span></a></li>
                            </ul>
                        </nav>
                    </div>
                    <!-- <div class="button_placeholder">
                        <div class="login_btn_placeholder">
                            <button type="button" class="login_btn"><span>Login</span></button>
                        </div>
                        <div class="register_btn_placeholder">
                            <button type="button" class="register_btn"><span>Register</span></button>
                        </div>
                    </div> -->
                </div>
            </div>
        </header>
        <div class="main_header_placeholder">
            <div class="main_header">
                <h1 class="main_title"><span>New Admission</span></h1>
                <h1 class="main_title"><span>School Name</span></h1>
            </div>
            <!-- <div class="sub_header">
                <p class="sub_title"><span>Discover a place where young minds flourish through </span></p>
                <p class="sub_title"><span>innovative education and community</span></p>
                <p class="sub_title"><span>engagement at our nurturing,</span></p>
                <p class="sub_title"><span> forward-thinking school</span></p>
            </div>
            <div class="explore_btn_placeholder">
                <a href="#"><button type="button" class="explore_btn"><span>Explore Now</span></button></a>
            </div> -->
        </div>
    </div>
    <div class="container white">
        <div class="contact-container">
            <div class="contact-card">
                <div class="icon">
                    <!-- Phone Icon SVG -->
                    <svg width="256px" height="100px" viewBox="0 0 24 24" fill="none"
                        xmlns="http://www.w3.org/2000/svg">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <path
                                d="M16.5562 12.9062L16.1007 13.359C16.1007 13.359 15.0181 14.4355 12.0631 11.4972C9.10812 8.55901 10.1907 7.48257 10.1907 7.48257L10.4775 7.19738C11.1841 6.49484 11.2507 5.36691 10.6342 4.54348L9.37326 2.85908C8.61028 1.83992 7.13596 1.70529 6.26145 2.57483L4.69185 4.13552C4.25823 4.56668 3.96765 5.12559 4.00289 5.74561C4.09304 7.33182 4.81071 10.7447 8.81536 14.7266C13.0621 18.9492 17.0468 19.117 18.6763 18.9651C19.1917 18.9171 19.6399 18.6546 20.0011 18.2954L21.4217 16.883C22.3806 15.9295 22.1102 14.2949 20.8833 13.628L18.9728 12.5894C18.1672 12.1515 17.1858 12.2801 16.5562 12.9062Z"
                                fill="#c1dff7"></path>
                        </g>
                    </svg>
                </div>
                <h3>Call Us</h3>
                <p>08886512233</p>
            </div>
            <div class="contact-card middle">
                <div class="icon">
                    <!-- Location Icon SVG -->
                    <svg width="256px" height="150px" viewBox="-1.44 -1.44 18.88 18.88"
                        xmlns="http://www.w3.org/2000/svg" fill="#000000" stroke="whitesmoke" transform="rotate(0)"
                        stroke-width="0.304">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="whitesmoke"
                            stroke-width="0.032"></g>
                        <g id="SVGRepo_iconCarrier">
                            <path
                                d="m 8 0 c -3.3125 0 -6 2.6875 -6 6 c 0.007812 0.710938 0.136719 1.414062 0.386719 2.078125 l -0.015625 -0.003906 c 0.636718 1.988281 3.78125 5.082031 5.625 6.929687 h 0.003906 v -0.003906 c 1.507812 -1.507812 3.878906 -3.925781 5.046875 -5.753906 c 0.261719 -0.414063 0.46875 -0.808594 0.585937 -1.171875 l -0.019531 0.003906 c 0.25 -0.664063 0.382813 -1.367187 0.386719 -2.078125 c 0 -3.3125 -2.683594 -6 -6 -6 z m 0 3.691406 c 1.273438 0 2.308594 1.035156 2.308594 2.308594 s -1.035156 2.308594 -2.308594 2.308594 c -1.273438 -0.003906 -2.304688 -1.035156 -2.304688 -2.308594 c -0.003906 -1.273438 1.03125 -2.304688 2.304688 -2.308594 z m 0 0"
                                fill="rgb(193, 223, 247)"></path>
                        </g>
                    </svg>
                </div>
                <div class="address_header">
                    <h3>Address</h3>
                </div>
                <div class="address">
                    <p>Flat/Door/Block No. 4-70-7, PEDDA WALTAIR, BESIDE BABA BAZAAR, ANDHRA PRADESH,
                        VISAKHAPATNAM, Pin 530017</p>
                </div>
            </div>
            <div class="contact-card">
                <div class="icon">
                    <!-- Email Icon SVG -->
                    <svg width="256px" height="100px" viewBox="0 -3.5 32 32" version="1.1"
                        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                        xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" fill="#000000">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier">
                            <title>mail</title>
                            <desc>Created with Sketch Beta.</desc>
                            <defs> </defs>
                            <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"
                                sketch:type="MSPage">
                                <g id="Icon-Set-Filled" sketch:type="MSLayerGroup"
                                    transform="translate(-414.000000, -261.000000)" fill="#c1dff7">
                                    <path
                                        d="M430,275.916 L426.684,273.167 L415.115,285.01 L444.591,285.01 L433.235,273.147 L430,275.916 L430,275.916 Z M434.89,271.89 L445.892,283.329 C445.955,283.107 446,282.877 446,282.634 L446,262.862 L434.89,271.89 L434.89,271.89 Z M414,262.816 L414,282.634 C414,282.877 414.045,283.107 414.108,283.329 L425.147,271.927 L414,262.816 L414,262.816 Z M445,261 L415,261 L430,273.019 L445,261 L445,261 Z"
                                        id="mail" sketch:type="MSShapeGroup"> </path>
                                </g>
                            </g>
                        </g>
                    </svg>
                </div>
                <h3>E-mail</h3>
                <p>info@vizag.org</p>
            </div>
        </div>
        <div class="admission_form_placeholder">
            <form method="post" action="{% url 'admission' %}" class="admission_form">
                {% csrf_token %}
                <div class="form-group">
                    <!-- <label for="id_name">Name</label> -->
                    <input type="text" id="id_name" name="name" required placeholder="Enter Name">
                </div>
                <div class="form-group">
                    <!-- <label for="id_dob">Date Of Birth</label> -->
                    <input type="date" id="id_dob" name="date_of_birth" required placeholder="Enter Date Of Birth">
                </div>
                <div class="form-group">
                    <!-- <label for="id_email">Email</label> -->
                    <input type="email" id="id_email" name="email" required placeholder="Enter Email Id">
                </div>
                <div class="form-group">
                    <!-- <label for="id_address">Address</label> -->
                    <textarea id="id_address" name="address" required placeholder="Enter Address"></textarea>
                </div>
                <div class="form-group">
                    <!-- <label for="id_coa">Class Of Admission</label> -->
                    <input type="text" id="id_coa" name="class_of_admission" required placeholder="Enter Class For Admission">
                </div>
                <div class="form-group">
                    <!-- <label for="id_ps">Previous School Name</label> -->
                    <input type="text" id="id_ps" name="previous_school" required placeholder="Enter Previous School Name">
                </div>
                <div class="form-group">
                    <!-- <label for="id_pa">Parent Name</label> -->
                    <input type="text" id="id_pa" name="parent_name" required placeholder="Enter Parent Name">
                </div>
                <div class="form-group">
                    <!-- <label for="id_pc">Parent Contact Number</label> -->
                    <input type="number" id="id_pc" name="parent_contact" required placeholder="Enter Parent Phone Number">
                </div>
                <button type="submit" value="Submit">Submit</button>
            </form>
        </div>
    </div>
    <br><br>
    <footer>
        <div class="footer-container">
            <!-- Logo and School Name -->
            <div class="footer-logo">
                <img src="{% static 'sms/img/school-logo (2).png' %}" alt="School Logo">
                <h1>High School</h1>
            </div>
            <!-- Navigation Links -->
            <nav class="footer-nav">
                <a href="{% url 'home' %}">Home</a>
                <a href="{% url 'about' %}">About</a>
                <a href="{% url 'contact' %}">Contact</a>
                <a href="{% url 'admission' %}">New Admission</a>
            </nav>
            <!-- Footer Description -->
            <p class="footer-description">
                Welcome to High School, where we nurture young minds to achieve their full potential.
                Join our vibrant community dedicated to excellence in education, personal growth, and lifelong learning.
                Contact us today!
            </p>
            <!-- Social Media Icons -->
            <div class="footer-social">
                <a href="#"><img src="https://img.icons8.com/ios-filled/24/FFFFFF/facebook-new.png" alt="Facebook"></a>
                <a href="#"><img src="https://img.icons8.com/ios-filled/24/FFFFFF/twitter.png" alt="Twitter"></a>
                <a href="#"><img src="https://img.icons8.com/ios-filled/24/FFFFFF/instagram-new.png"
                        alt="Instagram"></a>
                <a href="#"><img src="https://img.icons8.com/ios-filled/24/FFFFFF/linkedin.png" alt="LinkedIn"></a>
            </div>
        </div>
    </footer>

    <script src="{% static 'sms/js/navbar.js' %}"></script>
    <script src="{% static 'sms/js/mobileview.js' %}"></script>
</body>

</html>